package com.vigorchip.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.vigorchip.db.entity.FoodHelpBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "tb_foodhelp".
*/
public class FoodHelpBeanDao extends AbstractDao<FoodHelpBean, Long> {

    public static final String TABLENAME = "tb_foodhelp";

    /**
     * Properties of entity FoodHelpBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Fid = new Property(1, String.class, "fid", false, "FID");
        public final static Property Cur_step = new Property(2, String.class, "cur_step", false, "CUR_STEP");
        public final static Property Explanation = new Property(3, String.class, "explanation", false, "EXPLANATION");
    };


    public FoodHelpBeanDao(DaoConfig config) {
        super(config);
    }
    
    public FoodHelpBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"tb_foodhelp\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"FID\" TEXT," + // 1: fid
                "\"CUR_STEP\" TEXT," + // 2: cur_step
                "\"EXPLANATION\" TEXT);"); // 3: explanation
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"tb_foodhelp\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FoodHelpBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String fid = entity.getFid();
        if (fid != null) {
            stmt.bindString(2, fid);
        }
 
        String cur_step = entity.getCur_step();
        if (cur_step != null) {
            stmt.bindString(3, cur_step);
        }
 
        String explanation = entity.getExplanation();
        if (explanation != null) {
            stmt.bindString(4, explanation);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FoodHelpBean readEntity(Cursor cursor, int offset) {
        FoodHelpBean entity = new FoodHelpBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // fid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // cur_step
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // explanation
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FoodHelpBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCur_step(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setExplanation(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FoodHelpBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FoodHelpBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
