package com.vigorchip.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * auto greenDao generate javaBean by MonkeyKing
 */
public class CategoryBean {

    private Long id;
    private String fid;
    private String parent_id;
    private String name;
    private String bg_pic;
    private String totlestep;
    private String p2totletime1;
    private String p4totletime1;
    private String p6totletime1;
    private String p2totletime2;
    private String p4totletime2;
    private String p6totletime2;

    public CategoryBean() {
    }

    public CategoryBean(Long id) {
        this.id = id;
    }

    public CategoryBean(Long id, String fid, String parent_id, String name, String bg_pic, String totlestep, String p2totletime1, String p4totletime1, String p6totletime1, String p2totletime2, String p4totletime2, String p6totletime2) {
        this.id = id;
        this.fid = fid;
        this.parent_id = parent_id;
        this.name = name;
        this.bg_pic = bg_pic;
        this.totlestep = totlestep;
        this.p2totletime1 = p2totletime1;
        this.p4totletime1 = p4totletime1;
        this.p6totletime1 = p6totletime1;
        this.p2totletime2 = p2totletime2;
        this.p4totletime2 = p4totletime2;
        this.p6totletime2 = p6totletime2;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFid() {
        return fid;
    }

    public void setFid(String fid) {
        this.fid = fid;
    }

    public String getParent_id() {
        return parent_id;
    }

    public void setParent_id(String parent_id) {
        this.parent_id = parent_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBg_pic() {
        return bg_pic;
    }

    public void setBg_pic(String bg_pic) {
        this.bg_pic = bg_pic;
    }

    public String getTotlestep() {
        return totlestep;
    }

    public void setTotlestep(String totlestep) {
        this.totlestep = totlestep;
    }

    public String getP2totletime1() {
        return p2totletime1;
    }

    public void setP2totletime1(String p2totletime1) {
        this.p2totletime1 = p2totletime1;
    }

    public String getP4totletime1() {
        return p4totletime1;
    }

    public void setP4totletime1(String p4totletime1) {
        this.p4totletime1 = p4totletime1;
    }

    public String getP6totletime1() {
        return p6totletime1;
    }

    public void setP6totletime1(String p6totletime1) {
        this.p6totletime1 = p6totletime1;
    }

    public String getP2totletime2() {
        return p2totletime2;
    }

    public void setP2totletime2(String p2totletime2) {
        this.p2totletime2 = p2totletime2;
    }

    public String getP4totletime2() {
        return p4totletime2;
    }

    public void setP4totletime2(String p4totletime2) {
        this.p4totletime2 = p4totletime2;
    }

    public String getP6totletime2() {
        return p6totletime2;
    }

    public void setP6totletime2(String p6totletime2) {
        this.p6totletime2 = p6totletime2;
    }

}
