package com.vigorchip.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * auto greenDao generate javaBean by MonkeyKing
 */
public class FoodHelpBean {

    private Long id;
    private String fid;
    private String cur_step;
    private String explanation;

    public FoodHelpBean() {
    }

    public FoodHelpBean(Long id) {
        this.id = id;
    }

    public FoodHelpBean(Long id, String fid, String cur_step, String explanation) {
        this.id = id;
        this.fid = fid;
        this.cur_step = cur_step;
        this.explanation = explanation;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFid() {
        return fid;
    }

    public void setFid(String fid) {
        this.fid = fid;
    }

    public String getCur_step() {
        return cur_step;
    }

    public void setCur_step(String cur_step) {
        this.cur_step = cur_step;
    }

    public String getExplanation() {
        return explanation;
    }

    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }

}
